add `fund_user` sndev command

diff --git a/sndev b/sndev
--- a/sndev
+++ b/sndev
@@ -219,6 +219,43 @@ USAGE
   echo "$help"
 }
 
+sndev__fund_user() {
+  shift
+  if [ -z "$1" ]; then
+    echo "<nym> argument required"
+    sndev__help_fund_user
+    exit 1
+  fi
+  if [ -z "$2" ]; then
+    echo "<msats> argument required"
+    sndev__help_fund_user
+    exit 2
+  fi
+  re='^[0-9]+$'
+  if ! [[ $2 =~ $re ]]; then
+   echo "<msats> is not a positive integer"
+   sndev__help_fund_user
+   exit 3
+  fi
+  docker__exec db psql -U sn -d stackernews -q <<EOF
+    UPDATE users set msats = msats + $2 where name = '$1';
+EOF
+}
+
+sndev__help_fund_user() {
+  help="
+fund a nym without using an LN invoice (local only)
+
+USAGE
+  $ sndev fund_user <nym> <msats>
+
+  <nym> - the name of the user you want to fund
+  <msats> - the amount of millisatoshis to add to the account. Must be a positive integer
+"
+
+  echo "$help"
+}
+
 sndev__fund() {
   shift
   docker__stacker_lnd -t payinvoice "$@"
